on:
  push:
  branches: main
  pull_request:
    branches: main

name: Render site

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.17.1'
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.2'
      - run: echo "# Test" | pandoc -t html


