on:
  push:
  branches: main
  pull_request:
    branches: main

name: Render site

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
    
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.17.1'
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.2'

      - name: Install dependencies
        run: |
          install.packages("rmarkdown")
          install.packages("distill")
          install.packages("devtools")
         shell: Rscript {0}
    
      - name: Render Site
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'
      - name: Commit results
        run: |
          git add -A
          git commit -m 'Rebuild site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"


